# Generated by Django 4.2.4 on 2023-08-28 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing', '0001_initial'),
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mail',
            name='client_to_message',
            field=models.ManyToManyField(related_name='client_to_message', to='client.mailingclient', verbose_name='Клиенты'),
        ),
        migrations.AddField(
            model_name='mail',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings'),
        ),
    ]
