# Generated by Django 4.2.4 on 2023-08-31 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingsettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылки'},
        ),
    ]
